"""Build a single-file Windows .exe with PyInstaller.

Run:
    pip install pyinstaller
    python build_exe.py               # standard build, no debug logging
    python build_exe.py --debug-logging  # enables gui.log in the built exe

Produces `dist/MPCFillToPDF.exe`. The .exe is portable: drop it in any
folder and it will create `MPCFillToPDF/archivos generados/` and
`MPCFillToPDF/procesamiento/` next to itself.

Debug logging
-------------
Pass `--debug-logging` to bake `gui/_build_flags.py` with `DEBUG_LOGGING = True`.
Without the flag the file is written with `False` and no `gui.log` is created.
`gui/_build_flags.py` is listed in .gitignore and deleted after the build.

SmartScreen / antivirus false positives
---------------------------------------
This build uses three measures to minimise false-positive AV detections:

1. UPX disabled (--noupx): UPX compression is a major heuristic trigger used
   by many AV engines.  Disabling it increases binary size ~10 % but
   significantly reduces detections.

2. Stdlib bloat excluded: modules never used at runtime are stripped via
   --exclude-module so the archive surface is smaller.

3. Windows version metadata (version_file.txt) reduces (but does not
   eliminate) the "unknown publisher" SmartScreen prompt on first launch.

If detections persist, the next most effective step is rebuilding PyInstaller's
bootloader from source so it gets a unique hash AV vendors don't yet flag:

    # One-time setup (requires a C compiler; on Windows install
    # "Visual Studio Build Tools" with the C++ workload).
    git clone https://github.com/pyinstaller/pyinstaller.git
    cd pyinstaller/bootloader
    python ./waf all
    cd ..
    pip install --upgrade .

After that, run `python build_exe.py` as usual.

For any remaining detections after the above steps, submit the binary as a
false positive directly to the vendors:
  - Microsoft Defender / SmartScreen: https://www.microsoft.com/wdsi/filesubmission
  - Bkav: https://www.bkav.com.vn/
  - Gridinsoft: support@gridinsoft.com
  - SecureAge: their analysis portal
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "MPCFillToPDF"
ENTRY = ROOT / "gui" / "main.py"
ASSETS = ROOT / "src" / "assets"
ICONS = ROOT / "icons"
RESOURCES = ROOT / "resources"
VERSION_FILE = ROOT / "version_file.txt"
BUILD_FLAGS_PATH = ROOT / "gui" / "_build_flags.py"


def _write_build_flags(debug_logging: bool) -> None:
    BUILD_FLAGS_PATH.write_text(
        f"# Auto-generated by build_exe.py — do not commit.\nDEBUG_LOGGING = {debug_logging}\n",
        encoding="utf-8",
    )
    print(f"Build flags written (DEBUG_LOGGING={debug_logging}) -> {BUILD_FLAGS_PATH.name}")


def _remove_build_flags() -> None:
    try:
        BUILD_FLAGS_PATH.unlink()
        print(f"Cleaned up {BUILD_FLAGS_PATH.name}")
    except FileNotFoundError:
        pass


def _check_paths() -> None:
    required = [ENTRY, ASSETS, ICONS, RESOURCES]
    if sys.platform == "win32":
        required.append(VERSION_FILE)
    missing = [p for p in required if not p.exists()]
    if missing:
        for p in missing:
            print(f"ERROR: ruta requerida no encontrada: {p}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build MPCFillToPDF.exe")
    parser.add_argument(
        "--debug-logging",
        action="store_true",
        help="Enable gui.log file logging in the built exe (default: off)",
    )
    cli_args = parser.parse_args()

    if shutil.which("pyinstaller") is None:
        print("pyinstaller not found. Install it with: pip install pyinstaller", file=sys.stderr)
        sys.exit(1)

    _check_paths()
    _write_build_flags(cli_args.debug_logging)

    sep = ";" if sys.platform == "win32" else ":"
    args = [
        "pyinstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--noupx",
        "--log-level=WARN",
        "--name",
        APP_NAME,
        f"--add-data={ASSETS}{sep}src/assets",
        f"--add-data={ICONS}{sep}icons",
        f"--add-data={RESOURCES}{sep}resources",
        "--hidden-import=PIL.Image",
        "--hidden-import=reportlab.pdfgen",
        # Strip stdlib modules that are never imported at runtime.
        # Reduces archive surface scanned by AV heuristics.
        "--exclude-module=unittest",
        "--exclude-module=doctest",
        "--exclude-module=pdb",
        "--exclude-module=difflib",
        "--exclude-module=ftplib",
        "--exclude-module=imaplib",
        "--exclude-module=smtplib",
        "--exclude-module=poplib",
        "--exclude-module=telnetlib",
        "--exclude-module=xmlrpc",
        "--exclude-module=http.server",
        "--exclude-module=tkinter.test",
        str(ENTRY),
    ]
    if sys.platform == "win32":
        args.append(f"--version-file={VERSION_FILE}")
        args.append("--hidden-import=windnd")
    print("Running:", " ".join(args))
    try:
        subprocess.run(args, check=True, cwd=ROOT)
    finally:
        _remove_build_flags()

    suffix = ".exe" if sys.platform == "win32" else ""
    print(f"\nBuilt: {ROOT / 'dist' / (APP_NAME + suffix)}")


if __name__ == "__main__":
    main()
