"""Build a single-file Windows .exe with PyInstaller.

Run:
    pip install pyinstaller
    python build_exe.py

Produces `dist/MPCFillToPDF.exe`. The .exe is portable: drop it in any
folder and it will create `out/` and `workdir/` next to itself.

API key embedding
-----------------
If `config.json` contains a valid `google_drive_api_key`, it is XOR-encoded
with a random mask and baked into `src/_bundled_key.py` before packaging.
PyInstaller bundles that module; at runtime the app decodes and uses the key
in memory.  The key never appears as a plain string inside the binary.

`src/_bundled_key.py` is listed in .gitignore and deleted after the build.

SmartScreen / antivirus false positives
---------------------------------------
This build embeds Windows version metadata via `version_file.txt`, which
reduces (but does not eliminate) the "unknown publisher" SmartScreen prompt
on first launch.

To reduce false positives further, you can rebuild PyInstaller's bootloader
from source so it has a unique hash that AV vendors don't yet flag:

    # One-time setup (requires a C compiler; on Windows install
    # "Visual Studio Build Tools" with the C++ workload).
    git clone https://github.com/pyinstaller/pyinstaller.git
    cd pyinstaller/bootloader
    python ./waf all
    cd ..
    pip install --upgrade .

After that, run `python build_exe.py` as usual.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP_NAME = "MPCFillToPDF"
ENTRY = ROOT / "gui" / "main.py"
ASSETS = ROOT / "src" / "assets"
ICONS = ROOT / "icons"
RESOURCES = ROOT / "resources"
VERSION_FILE = ROOT / "version_file.txt"
BUNDLED_KEY_PATH = ROOT / "src" / "_bundled_key.py"


def _embed_api_key() -> bool:
    """Read config.json, XOR-encode the API key, write src/_bundled_key.py.

    Returns True if a key was successfully embedded, False otherwise.
    The file must be deleted after the build regardless.
    """
    config_path = ROOT / "config.json"
    if not config_path.exists():
        print(
            "WARNING: config.json not found — API key will NOT be embedded.\n"
            "         Copy config.example.json to config.json and fill in your key."
        )
        return False

    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception as exc:
        print(f"WARNING: Could not parse config.json ({exc}) — API key not embedded.")
        return False

    key = str(data.get("google_drive_api_key", "")).strip()
    if not key or key.startswith("YOUR_"):
        print(
            "WARNING: google_drive_api_key is not set in config.json — "
            "API key will NOT be embedded."
        )
        return False

    key_bytes = key.encode("utf-8")
    mask = os.urandom(len(key_bytes))
    encoded = bytes(a ^ b for a, b in zip(key_bytes, mask))

    BUNDLED_KEY_PATH.write_text(
        "# Auto-generated by build_exe.py — do not commit.\n"
        f"_E = {encoded!r}\n"
        f"_M = {mask!r}\n"
        "\n"
        "def _get_key() -> str:\n"
        "    return bytes(a ^ b for a, b in zip(_E, _M)).decode('utf-8')\n",
        encoding="utf-8",
    )
    print(f"API key embedded (XOR-obfuscated) -> {BUNDLED_KEY_PATH.name}")
    return True


def _remove_bundled_key() -> None:
    try:
        BUNDLED_KEY_PATH.unlink()
        print(f"Cleaned up {BUNDLED_KEY_PATH.name}")
    except FileNotFoundError:
        pass


def main() -> None:
    if shutil.which("pyinstaller") is None:
        print("pyinstaller not found. Install it with: pip install pyinstaller", file=sys.stderr)
        sys.exit(1)

    _embed_api_key()

    args = [
        "pyinstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--name",
        APP_NAME,
        f"--version-file={VERSION_FILE}",
        f"--add-data={ASSETS}{';' if sys.platform == 'win32' else ':'}src/assets",
        f"--add-data={ICONS}{';' if sys.platform == 'win32' else ':'}icons",
        f"--add-data={RESOURCES}{';' if sys.platform == 'win32' else ':'}resources",
        # Make sure these packages are bundled even when discovered indirectly
        "--hidden-import=PIL.Image",
        "--hidden-import=reportlab.pdfgen",
        "--hidden-import=gdown",
        "--hidden-import=windnd",
        str(ENTRY),
    ]
    print("Running:", " ".join(args))
    try:
        subprocess.run(args, check=True, cwd=ROOT)
    finally:
        _remove_bundled_key()

    print(f"\nBuilt: {ROOT / 'dist' / (APP_NAME + '.exe')}")


if __name__ == "__main__":
    main()
