import json
import logging
from pathlib import Path

_log = logging.getLogger(__name__)
_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def get_drive_api_key() -> str | None:
    """Return the Google Drive API key, or None if not configured.

    Resolution order:
    1. src._bundled_key — generated by build_exe.py and bundled into the .exe
       (XOR-obfuscated so the key is not a plain string in the binary).
    2. config.json in the project root — used when running from source.
       This file must NOT be committed; copy config.example.json to get started.
    """
    try:
        from src._bundled_key import _get_key  # noqa: PLC0415

        key = _get_key()
        if key:
            return key
    except ImportError:
        pass

    config_path = _PROJECT_ROOT / "config.json"
    if config_path.exists():
        try:
            data = json.loads(config_path.read_text(encoding="utf-8"))
            key = str(data.get("google_drive_api_key", "")).strip()
            if key and not key.startswith("YOUR_"):
                return key
        except Exception as exc:
            _log.warning("Could not read config.json: %s", exc)

    return None
